export const BaseLang =
    {
        'es': {
            'lang-error':'No se pudo encontrar el lang',
            'lang-param-error':'Faltan parámetros en el langService',
            'usuarioLogin': 'Por favor introduzca un usuario valido.',
            'usuarioFormLabel': 'Usuario',
            'usuarioHintLabel' : 'Ingrese el nombre de usuario.',
            'passwordLogin': 'Por favor introduzca un password valido.',
            'passwordFormLabel': 'Contrasena',
            'passwordHintLabel': 'Ingrese la contrasena',
            'btnLogin' : 'Ingresar',
            'btnCancel' : 'Cancelar',
            'loginFallido': 'Contrasena y/o usuario incorrectos. Por favor intente de nuevo.',
            'loginExitoso': 'Autenticacion exitosa.',
            'loginMensaje': 'Iniciar Sesion',
            'logoutMensaje': 'Cerrar Sesion',
            'tit-autenticacion': 'Autenticación',
            'loginCerrado': 'Su sesion ha sido cerrada.',
            'tit-info-sistema':'Información del sistema',
            'msg-copyright':'Copyright © Segip ' + new Date().getFullYear(),
            'msg-version': 'Versión',
            'lbl-lenguaje':'Lenguaje'
        },
        'en': {
            'lang-error':'Lang not found',
            'usuarioLogin': 'Please enter a valid username',
            'usuarioFormLabel': 'Username',
            'usuarioHintLabel' : 'Enter the username',
            'passwordLogin': 'Please enter a valid password',
            'passwordFormLabel': 'Password',
            'passwordHintLabel': 'Min 6 characters',
            'btnLogin': 'Log In',
            'btnCancel' : 'Cancel',
            'loginFallido' : 'Incorrect password or username entered. Please try again.',
            'loginExitoso' : 'Log in successfully',
            'loginMensaje': 'Log In',
            'logoutMensaje': 'Log Out',
            'tit-autenticacion': 'Login',
            'loginCerrado': 'Log out successfully',
            'tit-info-sistema':'System info',
            'msg-copyright':'Copyright © Segip ' + new Date().getFullYear(),
            'msg-version': 'Version',
            'lbl-lenguaje':'Language'
        }
    };
